### ISSUE TITLE
Pagina now-showing crasht

### ISSUE THREAD

**Issue by RobBosman** [Cerios/cerioscoop-web#5]
Sinds vandaag (dus sinds 2016-07-01, hint, hint) gaat er iets mis op pagina /now-showing.jsp:

![image](https://cloud.githubusercontent.com/assets/1183407/16533749/427e4574-3fdb-11e6-96c6-a7716711ea1a.png)

```
[ERROR   ] SRVE0777E: Exception thrown by application class 'com.ibm._jsp._now_2D_showing._jspService:156'
java.lang.NullPointerException
    at com.ibm._jsp._now_2D_showing._jspService(_now_2D_showing.java:156)
    at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:101)
    at [internal classes]
```

**Comment by FaustXVII** [comment]
Ik zal er zo naar kijken =D

**Comment by FaustXVII** [comment]
De laatste commit dat vind is van 3 dagen geleden. Mis ik wat hier?

**Comment by RobBosman** [comment]
Ha ha, klopt. En toch werkt 't ineens niet meer!

Met de debugger kun je zien wat er mis gaat. Zet een break point op regel 80 van `now_showing.jsp` en (her)start de server in debug-mode. Laad de NowShowing-pagina zodat het programma in die regel stopt en check dan in de _Variables_ view wat de waarden van alle variabelen zijn. Je zult zien dat `firstShowing` **null** is...

![image](https://cloud.githubusercontent.com/assets/1183407/16542201/bb75a94e-409f-11e6-95b7-c9ed64c2a507.png)

**Comment by FaustXVII** [comment]
firstShowing is bij mij niet null.
Alleen merk ik wel dat hij hem er later wel uit klapt (regel 109 bij mij) in de loop.
Ik heb ze commits op git nog door gekeken maar ik zie alleen maar renamings in deze class.
Zie ik iets over het hoofd hier?

![image](https://cloud.githubusercontent.com/assets/14161749/16636196/e494ef94-43d6-11e6-8e5a-286c74686624.png)

**Comment by RobBosman** [comment]
Bij mij gaat het nog steeds mis, ook nadat ik alles uit GitHub heb gerefreshed:
![image](https://cloud.githubusercontent.com/assets/1183407/16636442/710a6c78-43d8-11e6-80d0-38b7a99f45ce.png)
Ik vermoed dat je een of meer nieuwe 'showings' hebt ingevoerd voordat je dit ging debuggen. Het probleem heeft namelijk te maken met de vulling van tabel `show`: de datum van alle oorspronkelijke records was 2016-07-01, dus die records zijn inmiddels allemaal history. Daarom kan er geen `firstShowing` movie worden gevonden (**null**) en treedt een error op.

**Comment by MarcelGroothuis** [comment]
showings in the passed no longer result in a crash

**Comment by MarcelGroothuis** [comment]
still crashes when all showings are in the passed and there is nothing to show for !
